[project]
name = "ml-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.16",
    "mlflow>=3.1.4",
    "mysqlclient>=2.2.7",
    "psycopg2-binary>=2.9.10",
    "seaborn>=0.13.2",
]
